/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_com_example_MyObject
#define DBUS_GLIB_CLIENT_WRAPPERS_com_example_MyObject

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
com_example_MyObject_many_args (DBusGProxy *proxy, const guint IN_x, const char * IN_str, const gdouble IN_trouble, gdouble* OUT_d_ret, char ** OUT_str_ret, GError **error)

{
  return dbus_g_proxy_call (proxy, "ManyArgs", error, G_TYPE_UINT, IN_x, G_TYPE_STRING, IN_str, G_TYPE_DOUBLE, IN_trouble, G_TYPE_INVALID, G_TYPE_DOUBLE, OUT_d_ret, G_TYPE_STRING, OUT_str_ret, G_TYPE_INVALID);
}

typedef void (*com_example_MyObject_many_args_reply) (DBusGProxy *proxy, gdouble OUT_d_ret, char * OUT_str_ret, GError *error, gpointer userdata);

static void
com_example_MyObject_many_args_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gdouble OUT_d_ret;
  char * OUT_str_ret;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_DOUBLE, &OUT_d_ret, G_TYPE_STRING, &OUT_str_ret, G_TYPE_INVALID);
  (*(com_example_MyObject_many_args_reply)data->cb) (proxy, OUT_d_ret, OUT_str_ret, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
com_example_MyObject_many_args_async (DBusGProxy *proxy, const guint IN_x, const char * IN_str, const gdouble IN_trouble, com_example_MyObject_many_args_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "ManyArgs", com_example_MyObject_many_args_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_UINT, IN_x, G_TYPE_STRING, IN_str, G_TYPE_DOUBLE, IN_trouble, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_com_example_MyObject */

G_END_DECLS
